channels:
- anaconda
- conda-forge
dependencies:
- python=3.9.13
- pip:
  -  matplotlib==3.5.2
  -  numpy==1.21.5
  -  pandas==1.4.4
  -  scikit-learn==1.0.2
  -  seaborn==0.11.2
name: azureml_2d0fd20031db3baaed8684d5f08fe619
